services:
  # client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/algoarena
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - judge0
      - mongo
      - redis

  judge0:
    image: judge0/judge0:latest
    ports:
      - "2358:2358"
    restart: unless-stopped
    # Add any required environment variables for judge0 here

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

networks:
  default:
    driver: bridge
