'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./utils/Nav";
import EditorProvider from "./lib/contexts/editorContext";
import StoreProvider from "./StoreProvider";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "AlgoArena",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const route = usePathname();

  const nonav = ["/Reverify","/Forgotpassword/Magiclink/login"]
  console.log(nonav.some(n=>!route.startsWith(n)))


  return (
    <StoreProvider>
      <EditorProvider>
    <html lang="en"
    // className=" select-none"
    >
      <head>
      <link
            href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"
            rel="stylesheet"
        />
         <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz" crossOrigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        {
          !nonav.some(n=>route.startsWith(n)) && <Nav />
        }
        
        {children}
      </body>
    </html>
    </EditorProvider>
    </StoreProvider>
  );
}
